#!/bin/sh +x

multilog_err=1
multilog_cmd="multilog s16777215 n2 '!tai64nlocal' /opt/orbs/logs"

while [[ "${multilog_err}" -ne "0" ]]; do
    sleep 1
    echo "signer-service starting up.." | $multilog_cmd
    multilog_err=$?
done

echo "Running signer-service.."

/opt/orbs/orbs-signer $@ 2>&1 | $multilog_cmd 2>&1