#!/bin/sh +x

multilog_err=1
multilog_cmd="multilog s16777215 n2 '!tai64nlocal' /opt/orbs/logs"

while [[ "${multilog_err}" -ne "0" ]]; do
    sleep 1
    echo "signer-service starting up.." | $multilog_cmd
    multilog_err=$?
done

echo "Running signer-service.. on 80 and 7777"

socat TCP4-LISTEN:7777,reuseaddr,fork TCP4:127.0.0.1:80 > /dev/null 2>&1 &
exec /opt/orbs/orbs-signer $@ 2>&1 | $multilog_cmd
